name: islam_pedia
description: Islam Pedia

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  lottie: ^1.4.2
  simple_shadow: ^0.3.0
  go_router: ^4.3.0
  buttons_tabbar: ^1.3.6
  flutter_hooks: ^0.18.5+1
  auto_size_text: ^3.0.0
  hooks_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen: ^4.3.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/generated
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false

  colors:
    inputs:
      - assets/colors/color.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
